### ISSUE TITLE
`tabulateRecordA`

### ISSUE THREAD

**Issue by parsonsmatt** [parsonsmatt/prairie#1]
I should add a method to `Record`:

```haskell
class Record a where
    tabulateRecordA :: (Applicative m) => (forall ty. Field rec ty -> m ty) -> m rec
```

`tabulateRecord` is then a specialization of this to `Identity`, and it would allow folks to write neat stuff like:

```haskell
parseRecord :: (FieldDict FromJSON a) => Parser a
parseRecord = 
    withObject "Record" \o -> 
        tabulateRecordA \field ->
            withFieldDict @FromJSON field do
                o .: recordFieldLabel field
```

**Comment by treeowl** [comment]
Along with all the other reasons to do this, working in the `Solo` applicative is a good way to avoid accidentally filling a record with thinks (especially what I call "stupid thunks": ones that are completely free to evaluate but aren't selector thunks).
