### ISSUE TITLE
Higher-kinded records

### ISSUE THREAD

**Issue by mixphix** [parsonsmatt/prairie#14]
I've been wanting to scale this approach to structuring data using higher-kinded types (HKTs). These are ostensibly record types themselves, but their entries are now _actions_ rather than _values_, and the type constructor you want to act under gets passed as an argument to the HKT. The types in the resulting data family all have the same shape, but now their normal contents (`Identity`) may be missing or replaced (`Maybe`, `Const a`), or have other interesting side effects (`FormResult`). Functions that swap out this constructor from underneath the HKT are of particular interest, and something like the following (and compile-time generation of its instances) would trivialize writing these sorts of functions linearly.

```hs
{-# LANGUAGE AllowAmbiguousTypes #-}
{-# OPTIONS_GHC -Wno-orphans #-}

module Data.RecordB where

import Control.Lens
import Data.Kind
import Data.Text (Text, pack)
import Prairie

type RecordB :: ((Type -> Type) -> Type) -> Constraint
class RecordB b where
  type FieldB b :: Type -> Type
  recordFieldLensB ::
    forall f ty.
    (Applicative f) =>
    (FieldB b ty -> Lens' (b f) (f ty))
  tabulateRecordAB ::
    forall m f.
    (Applicative m) =>
    (forall ty. FieldB b ty -> m (f ty)) ->
    m (b f)
  recordFieldLabelB :: Field (b f) x -> Text
  default recordFieldLabelB :: (Show (Field (b f) x)) => Field (b f) x -> Text
  recordFieldLabelB = pack . show

tabulateRecordB ::
  (RecordB b) => (forall ty. FieldB b ty -> f ty) -> b f
tabulateRecordB k = runIdentity (tabulateRecordAB (Identity . k))
```

Unfortunately typing issues arise when trying to write the instance entailment `(RecordB b, Applicative f) => Record (b f)`. With the existing TH functions one might be able to declare `mkRecord ''(MyHKT Identity)` and `mkRecord ''(MyHKT Maybe)`, but this requires each instance to declare its own `Field` type (no small feat). The structure is shared throughout the bundle, but how do we relate `FieldB` and `Field`?

**Comment by parsonsmatt** [comment]
You may be interested in #5 - as it happens, `newtype Advanced f rec = Advanced (forall ty. Field rec ty -> f ty)` appears to be strictly more powerful than `HKD` approaches to this problem.

I haven't figured out a name I like for it - `Advanced` feels wrong, `HigherKinded f rec` almost works, `Decorated f rec` feels alright, `DistributeRec f rec` maybe? I'm not really sure.
